### ISSUE TITLE
Found:    "Functions" at 10:1 Expected: ("ArchiveEntry" | "Lemma" | "Theorem" | "Exercise") Hint: Try ("ArchiveEntry" | "Lemma" | "Theorem" | "Exercise")

### ISSUE THREAD

**Issue by chuyanga** [IBM/AI-Descartes#2]
I'm sorry to bother you, but I encountered some issues while reproducing it. Could you please help me resolve them?

[launcher] Restarting KeYmaera X with sufficient stack space
/home/chuyang/software/java/jre1.8.0_371/bin/java -Xss20M -da -jar /home/chuyang/code/AI2/AI-Descartes/reasoning/src/keymaerax/keymaerax.jar -launch -tool mathematica -timeout 1200 -prove ../output/keymaera/keymaera_files/KeplerExperimentsBinaryStars/formula0__interval.kyx -out ../output/keymaera/keymaera_files/KeplerExperimentsBinaryStars/formula0__interval.kyp
KeYmaera X Prover 5.0.2
Use option -help for usage and license information
Exception in thread "main" 10:1 Error parsing archiveStart at 10:1
Found:    "Functions" at 10:1
Expected: ("ArchiveEntry" | "Lemma" | "Theorem" | "Exercise")
Hint: Try ("ArchiveEntry" | "Lemma" | "Theorem" | "Exercise")
in 10:1
Functions
^

input:  
Definitions
  Real G;
  Real pi;
  Real convP;
  Real convm2;
  Real convm1;
  Real convD;
  Real relerr;
End.
Functions
End.
ProgramVariables
  Real m1;
  Real m2;
  Real d;
  Real m1N;
  Real m2N;
  Real dN;
  Real P;
  Real d1;
  Real d2;
  Real w;
  Real Fg;
  Real Fc;
  Real PN;
End.
Problem
(
(
 m1>0 & m2>0 & P>0 & d2>0 & d1>0 & m1N>0 & m2N>0 & PN>0
 & G = (6.674 * 10^(-11)) & pi = (3.14)
 & ( m1 * d1 = m2 * d2 ) 
 & ( d = d1 + d2 )  
 & ( Fg = (G * m1 * m2) / d^2 ) 
 & ( Fc =  m2 * d2 * w^2 )
 & ( Fg =  Fc )
 & ( P = (2 * pi )/w )
 & convP = (365 * 24 * 60 * 60  )
 & convm1 = ( 1.9885 * 10^30 )
 & convm2 = ( 1.9885 * 10^30 )
 & convD = (1.496 * 10^11  )
 & m1N = m1 / convm1
 & m2N = m2 / convm2
 & dN = d / convD
 & PN = P / convP
 & m1N>=0.54 & m1N<=3.06
 & m2N>=0.5 & m2N<=1.97
 & dN>=38.235 & dN<=131.352
 & relerr = 0.5
)
->
(
abs( ( ( dN^(-2) * m1N^(-2) ) + ( dN^(-2) * m2N^(-2) ) - ( m1N^3 * m2N^2 ) + (( 0.4787 * dN^3 * m2N^(-1) ) + ( dN^2 * m2N^2 ))^(1/2) ) - PN ) / PN < relerr
)
)
End.

at edu.cmu.cs.ls.keymaerax.parser.ParseException$.apply(ParserErrors.scala:80)
at edu.cmu.cs.ls.keymaerax.parser.DLParser$.parseException(DLParser.scala:85)
at edu.cmu.cs.ls.keymaerax.parser.DLArchiveParser.$anonfun$archiveParser$1(DLArchiveParser.scala:67)
at edu.cmu.cs.ls.keymaerax.parser.DLArchiveParser.doParse(DLArchiveParser.scala:52)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parse(ArchiveParser.scala:428)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parse$(ArchiveParser.scala:427)
at edu.cmu.cs.ls.keymaerax.parser.DLArchiveParser.parse(DLArchiveParser.scala:46)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parse(ArchiveParser.scala:426)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parse$(ArchiveParser.scala:426)
at edu.cmu.cs.ls.keymaerax.parser.DLArchiveParser.parse(DLArchiveParser.scala:46)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parseFromFile(ArchiveParser.scala:442)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser.parseFromFile$(ArchiveParser.scala:437)
at edu.cmu.cs.ls.keymaerax.parser.DLArchiveParser.parseFromFile(DLArchiveParser.scala:46)
at edu.cmu.cs.ls.keymaerax.parser.ArchiveParser$.parseFromFile(ArchiveParser.scala:509)
at edu.cmu.cs.ls.keymaerax.cli.KeYmaeraXProofChecker$.$anonfun$prove$16(KeYmaeraXProofChecker.scala:174)
at scala.collection.immutable.List.map(List.scala:286)
at edu.cmu.cs.ls.keymaerax.cli.KeYmaeraXProofChecker$.prove(KeYmaeraXProofChecker.scala:174)
at edu.cmu.cs.ls.keymaerax.cli.KeYmaeraX$.runCommand(KeYmaeraX.scala:81)
at edu.cmu.cs.ls.keymaerax.launcher.KeYmaeraX$.main(KeYmaeraX.scala:120)
at edu.cmu.cs.ls.keymaerax.launcher.Main$.main(Main.scala:97)
at edu.cmu.cs.ls.keymaerax.launcher.Main.main(Main.scala)

**Comment by corneliocristina** [comment]
This error occurs with newer versions of KeYmaeraX. Try to use the version we recommend for the experiments: KeYmaeraX 4.9.3. You can download the right version from [here](https://github.com/LS-Lab/KeYmaeraX-release/releases)). With more recent versions you need to modify the code (e.g. adding `ArchiveEntry "entry_name"` at the beginning of the KeYmaera files). See [KeYmaeraX website](https://keymaerax.org) for more details.
